---
- hosts: localhost
  become: true
 
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        upgrade: "yes"
      changed_when: False  
  tasks:
    - include_vars: variables/docker_variables.yml
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include_vars: variables/drive_variables.yml
    - include: tasks/make_dir.yml
    - include: tasks/mount_drives.yml
    - include: tasks/docker_star_apps.yml
    - include: tasks/cron.yml 
