- name: Create folder for docker compose   
  file:
    path: /home/ansible/docker-compose      
    state: directory
    owner: ansible
    group: ansible
    mode: '0775'
   
- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/ansible/docker-compose/docker-compose.yml
    owner: ansible
    group: ansible
    mode: '0755'

      #- name: Create and start services
  #  community.docker.docker_compose:
    #    project_src: /home/ansible/docker-compose/docker-compose.yml
      #  register: output

- name: Start service
  docker_compose:
    project_src: /home/ansible/docker-compose/docker-compose.yml
    state: present
    service: service_name
    compose:
      command: up
      scale:
        service_name: 2

- name: Create Star Apps folder
  file: 
    path: /home/ansible/star-apps
    state: directory
    owner: ansible
    group: ansible
    mode: '0755'
