- name: Create folder for docker compose   
  file:
    path: /home/ansible/docker-compose      
    state: directory
    owner: ansible
    group: ansible
    mode: '0775'
   
- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/ansible/docker-compose/docker-compose.yml
    owner: ansible
    group: ansible
    mode: '0755'

      #- name: Create and start services
  #  community.docker.docker_compose:
    #    project_src: /home/ansible/docker-compose/docker-compose.yml
      #  register: output

- name: Start service
  command: docker-compose up -d
  args:
    chdir: /home/ansible/docker-compose

- name: Create Star Apps folder
  file: 
    path: /home/ansible/star-apps
    state: directory
    recurse: yes
    owner: ansible
    group: ansible
    mode: '0755'

- name: Create Coloudlfared Tunnel
  command: docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiNzAyYzUxZWY1MDFiOWJhYWMwYjE4YjIzN2I3NTBiZTMiLCJ0IjoiZjAwYjI0YTEtMDc5Yi00ODVkLWIwMDMtMzk5OGM3OGY2ZDZjIiwicyI6IlpXVXhNV1EwTURndE1UTTBPQzAwWWpGbExXSTNNelV0WW1Kak1UQm1OV001WlRkaiJ9
