#- name: Create downloader group
#  group:
#    name: downloader
#    state: present
#    gid: 1005

- name: Add users to the Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - ansible
    - "{{ admin_user }}"
    - chris


- name: Create folder for docker compose
  file:
    path: /home/ansible/docker-compose
    state: directory 
    owner: ansible
    group: ansible
    mode: '755'

- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/ansible/docker-compose/docker-compose.yml
    owner: ansible
    group: ansible
    mode: '664'

- name: Create Star Apps folder
  file: 
    path: /home/ansible/star-apps
    state: directory
    recurse: yes
    owner: ansible
    group: downloader
    mode: '775'

- name: Copy Starr App Config Files
  copy:
    src: files/star-apps/
    dest: /home/ansible/star-apps/
    owner: ansible
    group: downloader
    mode: '775'
    remote_src: true

- name: Decrypt Star Config Files
  shell: ansible-vault decrypt --vault-password-file /home/ansible/.vault_key "{{ item }}"
  no_log: True
  loop:
    - /home/ansible/star-apps/radarr/radarr_config.xml
    - /home/ansible/star-apps/sonarr/sonarr_config.xml
    - /home/ansible/star-apps/sabnzbd/sabnzbd_config.ini

      #- name: Decrypt Sonarr Config
      #  shell: ansible-vault decrypt --vault-password-file /home/ansible/.vault_key /home/ansible/star-apps/sonarr/config.xml
      #  no_log: True

      #- name: Decrypt Radarr Config
      #  shell: ansible-vault decrypt --vault-password-file /home/ansible/.vault_key /home/ansible/star-apps/sabnzbd/sabnzbd.ini
      #  no_log: True

- name: Rename Star Config files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    loop:
      - { src: '/home/ansible/star-apps/radarr/radarr_config.xml', dest: '/home/ansible/star-apps/radarr/config.xml' }
      - { src: '/home/ansible/star-apps/sonarr/sonarr_config.xml', dest: '/home/ansible/star-apps/sonarr/config.xml' }
      - { src: '/home/ansible/star-apps/sabnzbd/sabnzbd_config.ini', dest: '/home/ansible/star-apps/sabnzbd/sabnzbd.ini' }

- name: Update permissions on star app files
  file:
    path: "/home/ansible/star-apps/{{ item }}"
    owner: ansible
    group: downloader
    mode: '664'
  loop:
    - /radarr/config.xml
    - /sonarr/config.xml
    - /sabnzbd/sabnzbd.ini


- name: Start service
  command: docker-compose up -d
  args:
    chdir: /home/ansible/docker-compose

