- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/ansible/ansible_made_this_dir
    state: directory
    mode: '0775'

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /home/ansible/ansible_made_this_dir
    state: directory
    recurse: yes
    owner: ansible
    group: ansible

- name: Create mount point if it does not exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: 0775
  become: true
  become_user: ansible

- name: Recursively change ownership of mount point
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    recurse: yes
    owner: ansible
    group: ansible
