- name: Create mount point if it does not exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '755'
    owner: chris
    group: downloader
    recurse: yes
  
#- name: Recursively change ownership of mount point
#  ansible.builtin.file:
#    path: "{{ mountpoint }}"
#    state: directory
#    recurse: yes
#    owner: ansible
#    group: ansible
