- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    recurse: yes
    owner: ansible
    group: ansible
    mode: '775'

- name: mount network share
  mount:
    src: "{{ mynfs }}"
    path: "{{ mountpoint }}"
    fstype: nfs
    opts: "{{ myopts }}"
    state: mounted
