- name: mount network share
  mount:
    src: "{{ mynfs }}"
    path: "{{ mountpoint }}"
    fstype: nfs
    opts: "{{ myopts }}"
    state: mounted

- name: Recursively change ownership of download mount point
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    recurse: yes
    owner: ansible
    group: ansible
    mode: '755'
