- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install aptitude using apt
  ansible.builtin.apt:
    name: aptitude
    state: latest
  
- name: Install required system packages for Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - python3-setuptools
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - nfs-common
      - nfs4-acl-tools
  update_cache: true
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Install Python Docker module
  pip:
    name:
      - docker
      - docker-compose

        #- name: Add adminstrator to docker group
        #  user:
        #    name: "{{ admin_user }}"
        #    groups: docker
        #    append: yes
