- name: Install aptitude using apt
  ansible.builtin.apt:
    name: aptitude
    state: latest
  
- name: Install required system packages for Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
      - docker.io
      - docker-compose
      - nfs-common
      - nfs4-acl-tools
  when: ansible_os_family == 'Debian'

    #- name: Add Docker GPG key
    #  apt_key:
    # url: "{{ docker_gpg_url }}"
    #state: present

    #- name: Install Python Docker module
    # pip:
    # name:
    #  - docker
    #  - docker-compose

    #- name: Add users to docker group
    #  user:
    #    name: "{{ item }}" 
    #    groups: docker
      #    append: yes
      #  loop:
      #    - ansible
      #    - "{{ admin_user }}"
