- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - python3-setuptools
      - docker-ce
      - docker-ce-cl
      - containerd.io
    state: latest
    update_cache: true

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present


- name: Install Python Docker module
  pip:
    name:
      - docker
      - docker-compose

- name: Add adminstrator to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: utility present debian-like
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs4-acl-tools
    state: present
  when: ansible_os_family == 'Debian'
