- name: create ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '440'

- name: Add user to docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: yes
