- name: create downloader group
  group:
    name: downloader
    state: present

# name: ansible
- name: Add users to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - ansible
    - "{{ admin_user }}"
