---
version: "3.2"
services:
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks: 
      - docker_bridge
    ports:
      - 7878:7878
    environment:
      - PUID=1001
      - PGID=1005
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ansible/star-apps/radarr:/config
      - /mnt/downloads/data:/data

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge
    ports:
      - 8989:8989
    environment:
      - PUID=1001
      - PGID=1005
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ansible/star-apps/sonarr:/config
      - /mnt/downloads/data:/data
  
  nzbget:
    container_name: nazbget
    image: cr.hotio.dev/hotio/nzbget
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge
    ports:
      - 6789:6789
    environment:
      - PUID=1001
      - PGID=1005
      - UMSAK=022
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ansible/star-apps/nzbget:/config
      - /mnt/downloads/data:/data     
 
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge    
    ports:
      - 5454:5454
    volumes:
      - /home/ansible/star-apps/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id   

networks:
  docker_bridge:
    driver: bridge
